/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AddNumbers */

#ifndef _Included_AddNumbers
#define _Included_AddNumbers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AddNumbers
 * Method:    addNumbers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_AddNumbers_addNumbers
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
