/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Lab1 */

#ifndef _Included_Lab1
#define _Included_Lab1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Lab1
 * Method:    getArithmeticMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Lab1_getArithmeticMean
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
